[package]
name = "nirust"
version = "0.1.0"
authors = ["Nils Pukropp <nils.pukropp@outlook.de>"]
edition = "2018"


[dependencies]
tracing = "0.1.23"
tracing-subscriber = "0.2"
ytd-rs = "0.1.4"
lazy_static = "1.4.0"
regex = "1"
toml = "0.5"
fs_extra = "1.2.0"
tokio = { version = "1.12", features = ["full"] }
songbird = { version = "0.2.0", features = ["builtin-queue"] }
strum_macros = "0.22"
strum = { version = "0.22", features = ["derive"] }
serde = "1"
serde_json = "1"
image = "0.23.14"
rand = "0.8"
chrono = "0.4"
humantime = "2.1"
async-trait = "0.1"
reqwest = "0.11"
html-escape = "0.2"
url = "2.2"

[dependencies.serenity]
version = "0.10"
default-features = false
features = [
    "cache",
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "native_tls_backend", 
    "unstable_discord_api", 
    "voice", 
    "collector"
    ]
