[package]
name = "nirust"
version = "0.1.0"
authors = ["Nils Pukropp <nils.pukropp@outlook.de>"]
edition = "2018"


[dependencies]
dotenv = "0.15"
tracing = "0.1.23"
tracing-subscriber = "0.2"
# config = "0.11.0"
ytd-rs = "0.1.4"
lazy_static = "1.4.0"
regex = "1"
toml = "0.5"
# sha2 = "0.9.4"
fs_extra = "1.2.0"
serenity = { version = "0.10", default-features = false, features = ["cache" ,"framework" , "standard_framework" ,"client", "gateway", "rustls_backend", "model", "unstable_discord_api", "voice"] }
tokio = { version = "1.0", features = ["macros", "signal", "rt-multi-thread"] }
songbird = { version = "0.2.0", features = ["builtin-queue"] }
serde = "1.0"
image = "0.23.14"
rand = "0.8"
chrono = "0.4"
humantime = "2.1"
async-trait = "0.1"
